Updating style

diff --git a/benchmark b/benchmark
--- a/benchmark
+++ b/benchmark
@@ -4,19 +4,19 @@
 
 # check for appropriate files
 if [ ! -f benchmark ]; then
-    echo "Error: you must run this script from the tuningfork directory." >&2
-    exit 1
+  echo "Error: you must run this script from the tuningfork directory." >&2
+  exit 1
 elif [ ! -f tune ]; then
-    echo "Error: The tune shell script could not be found" >&2
-    exit 1
+  echo "Error: The tune shell script could not be found" >&2
+  exit 1
 fi
 
 # check for time utility
-hasTimeUtility=`which time 2>/dev/null`
+hasTimeUtility=$(which time 2>/dev/null)
 
-if [ -z "$hasTimeUtility" ]; then
-    # There is no time utility on the system
-    echo "You must have the utility 'time' to run this program" >&2
+if [ -z "${hasTimeUtility}" ]; then
+  # There is no time utility on the system
+  echo "You must have the utility 'time' to run this program" >&2
 fi
 
 # Begin benchmarks
@@ -25,12 +25,12 @@ echo "1 minute file"
 echo "10 minute file"
 out=`(time -p ./tune -d 600 -n 600sec.wav) 2>&1`
 echo "$out"
-lastTime=`echo "$out" | grep 'real'`
-lastTime=`echo "$lastTime" | sed 's/^.* \([0-9]\+\).*$/\1/'`
+lastTime=$(echo "$out" | grep 'real')
+lastTime=$(echo "${lastTime}" | sed 's/^.* \([0-9]\+\).*$/\1/')
 
-if [[ "$1" == "-f" ]] || [[ "$lastTime" -le 3 ]]; then
-    echo "100 minute file"
-    (time -p ./tune -d 6000 -n 6000sec.wav) 2>&1
+if [[ "$1" == "-f" ]] || [[ "${lastTime}" -le 3 ]]; then
+  echo "100 minute file"
+  (time -p ./tune -d 6000 -n 6000sec.wav) 2>&1
 else
-    echo "To run the 100 minute benchmark (1 GB), supply the -f flag"
+  echo "To run the 100 minute benchmark (1 GB), supply the -f flag"
 fi
diff --git a/tune b/tune
--- a/tune
+++ b/tune
@@ -3,7 +3,7 @@
 # A shell script to interface with tuningFork.c
 
 
-helpMenu()
+function helpMenu
 {
 # prints helpMenu output
 cat >&2 << HELPMESSAGE
@@ -25,51 +25,51 @@ duration=10
 fname="A440.wav"
 
 if [[ ! -f tf ]]; then # create the executable file
-    make
-	if [[ $? != 0 ]]; then # failed compilation
-		echo "Compilation of tuningFork.c failed"
-		echo "Exiting with status (1)"
-		exit 1
-	fi
+  make
+  if [[ $? != 0 ]]; then # failed compilation
+    echo "Compilation of tuningFork.c failed"
+    echo "Exiting with status (1)"
+    exit 1
+  fi
 fi
 
 # ./tf executable should exist
 
 if [ "$1" == "--help" ]; then
-	helpMenu # function call
-	exit 0
+  helpMenu # function call
+  exit 0
 fi
 # possibly change variables
 
 while getopts "hf:d:n:" OPTION; do
-	case $OPTION in
-		h)
-			helpMenu
-			exit 0
-			;;
-		f) # change frequency
-			freq=$OPTARG
-			;;
-		d) # set to overwrite mode
-			duration=$OPTARG
-			;;
-		n)
-			fname=$OPTARG
-			;;
-		?)
-			helpMenu # call funciton
-			exit 1
-			;;
-	esac
+  case $OPTION in
+    h)
+      helpMenu
+      exit 0
+      ;;
+    f) # change frequency
+      freq=$OPTARG
+      ;;
+    d) # set to overwrite mode
+      duration=$OPTARG
+      ;;
+    n)
+      fname=$OPTARG
+      ;;
+    ?)
+      helpMenu # call funciton
+      exit 1
+      ;;
+  esac
 done
 
 
 
 # output variables to stdout piped to ./tf
-echoString="$freq\n$duration\n$fname\n"
+echoString="${freq}\n${duration}\n${fname}\n"
 
 # -en interprets escape sequences and ensures only 1 newline at end
 # redirect output to black hole
-echo -en "$echoString" | ./tf >/dev/null
+echo -en "${echoString}" | ./tf >/dev/null
 
 exit 0
