Syntax error fixed in tuningFork.c, logic error fixed in tune script

diff --git a/tune b/tune
--- a/tune
+++ b/tune
@@ -22,7 +22,7 @@ fname="A440.wav"
 
 if [[ ! -f tf ]]; then # create the executable file
 	gcc -o tf tuningFork.c
-	if [[ $? = 0 ]]; then # failed compilation
+	if [[ $? != 0 ]]; then # failed compilation
 		echo "Compilation of tuningFork.c failed"
 		echo "Exiting with status (1)"
 		exit 1
